apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>{{ .Values.appTitle }}</title>
        <style>
            body {
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                font-family: Arial, sans-serif;
                font-size: 48px;
                background-color: {{ .Values.bgColor }};
                color: white;
            }
        </style>
    </head>
    <body>
        <div>{{ .Values.displayText }}</div>
    </body>
    </html>
