apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: html
        configMap:
          name: {{ .Values.appName }}-html
          items:
          - key: index.html
            path: index.html
      - name: nginx-conf
        configMap:
          name: {{ .Values.appName }}-html
          items:
          - key: nginx.conf
            path: nginx.conf
  strategy:
    blueGreen:
      activeService: {{ .Values.appName }}-active
      previewService: {{ .Values.appName }}-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 15
      scaleDownDelaySeconds: 30
