{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName }}
    alb.ingress.kubernetes.io/listen-ports: '{{ .Values.ingress.listenPorts }}'
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Values.appName }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}-active
            port:
              number: 80
{{- end }}
