{{- if .Values.targetGroupBinding.enabled }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ .Values.appName }}
spec:
  targetGroupARN: {{ required "targetGroupBinding.targetGroupARN is required when enabled" .Values.targetGroupBinding.targetGroupARN }}
  targetType: {{ .Values.targetGroupBinding.targetType }}
  serviceRef:
    name: {{ .Values.appName }}-active
    port: 80
{{- end }}
