apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-active
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-preview
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
