appName: web-app
replicaCount: 1

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

appTitle: "Web App"
bgColor: "#333333"
displayText: "Hello from web-app"

ingress:
  enabled: true
  scheme: internet-facing
  targetType: ip
  groupName: sbx-apps
  listenPorts: '[{"HTTP": 80}]'
