project:
  name: fake-demo

replicaCount: 1

image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

command:
  - sleep
  - "3600"