apiVersion: apps/v1
kind: Deployment
metadata:
  name: extremelybusy
  namespace: busy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extremelybusy
  template:
    metadata:
      labels:
        app: extremelybusy
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command:
          - sleep
          - "3600"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"